@startuml SSD-Success: Create Booking
title SSD-Success: Create Booking

actor Client as ":Client"
actor System as ":System"

System -> System: userType := getCurrentUserType()
Client <-- System: display Public operations
Client -> System: selectOperation(loginOperationId)
...
Client -> System: login(username, password)
Client <-- System: success
...
loop
System -> System: userType := getCurrentUserType()
Client <-- System: display Client operations
Client -> System: selectOperation(createBookingOperationId)
System -> System: clientViewPublicOfferings()
Client <-- System: display Public Offerings
Client -> System: createBooking(offeringId)
Client <-- System: success
end

@enduml