@startuml Domain Model
title Domain Model

hide empty members
skinparam linetype ortho

package Main {
    class Terminal {}
    class App {
        currentUser
    }

    class UserRecords as "Users::UserRecords"  {}
    class Client as "Users::Client" {}
    class Instructor as "Users::Instructor" {}

    class City {
        name
        province
    }
    class Location {
        facility
        roomName
        type
    }

    class Schedule {
        startDate
        endDate
    }
    class TimeSlot {
        day
        startTime
        endTime
    }

    class OfferingRecords {}
    class Offering {
        lesson
        maxCapacity
        /currentCapacity
        /isPrivate
    }

    class BookingRecords {}
    class Booking {}

    App "1" -up- "1" Terminal
    App -left- UserRecords
    App -- OfferingRecords
    App -- BookingRecords

    Location "*" -up-> "1" City: in

    Schedule *- TimeSlot: has

    Offering --* OfferingRecords
    Offering "1" -up-> "1" Schedule: at
    Offering "1" --> "1" Location: in

    Instructor "1" -- "*" City: availableIn
    Instructor "0..1" <-- "*" Offering: taughtBy

    Client "*" -- "*" Offering

    (Client, Offering) -- Booking
    Booking --* BookingRecords
}
@enduml