@startuml ERD for Database
title Lesson Scheduling System

skinparam linetype ortho

!define PK <&key>
!define FK <&link-intact>

entity City {
    PK CI_ID: int
    --
    CI_NAME: string
    CI_PROVINCE: string 
}

entity LocationType {
    PK LT_ID: int
    --
    LT_NAME: string
}

entity Location {
    PK L_ID: int
    --
    L_FACILITY: string
    L_ROOM_NAME: string
    FK LT_ID: int
    FK CI_ID: int
}

entity Admin {
    PK A_ID: int
    --
    A_NAME: string
    A_USERNAME: string
    A_PASSWORD: string
}
entity Client {
    PK C_ID: int
    --
    C_NAME: string
    C_USERNAME: string
    C_PASSWORD: string
    C_AGE: int
    FK GUARDIAN_ID: int
}

entity Instructor {
    PK I_ID: int
    --
    I_NAME: string
    I_USERNAME: string
    I_PASSWORD: string
    I_PHONE: string
}
entity InstructorCity{
    PK FK I_ID: int
    PK FK CI_ID: int
}

entity Specialization {
    PK S_ID: int
    --
    S_NAME: string
}
entity InstructorSpecialization {
    PK FK I_ID: int
    PK FK S_ID: int
}

entity Schedule {
    PK SC_ID: int
    --
    SC_START_DATE: Date
    SC_END_DATE: Date
}
entity TimeSlot {
    PK TS_ID: int
    --
    TS_DAY: DAY_OF_WEEK
    TS_START_TIME: Timestamp
    TS_END_TIME: Timestamp
    FK SC_ID: int
}

entity Offering {
    PK O_ID: int
    --
    O_LESSON: string
    O_MAX_CAPACITY: int
    O_CURRENT_CAPACITY: int
    O_IS_PRIVATE: boolean
    FK I_ID: int
    FK L_ID: int
    FK SC_ID: int
}

entity Booking {
    PK FK C_ID: int
    PK FK O_ID: int
}

' Relationships
Location ||--|| LocationType

Offering }o-up-|| Instructor
Offering ||--|{ Booking
Offering }o-|| Location
Offering ||--|| Schedule

Booking }|--|| Client

City ||-o{ Location
City ||-|{ InstructorCity

Schedule ||--|{ TimeSlot

Instructor ||-right-|{ InstructorCity
Instructor ||-left-|{ InstructorSpecialization

InstructorSpecialization }|--|| Specialization

' Position Admin
Location ||-|| Empty
Empty -- Admin
hide Empty
@enduml
