@startuml Lesson_Management_System_Sequence_Diagram_

actor Admin
actor Instructor
participant System
participant Offering

Admin -> System: newOffering(Location, Schedule, Lesson)
System -> System: validate()
alt Success
    System -> Offering: saveDetails(Location, Schedule, Lesson)
    Offering --> System: Creation Confirmation
    System --> Admin: Creation Confirmation
else Failure
    System --> Admin: Error message
end

Admin -> System: viewOfferings()
System -> Offering: getOfferings()
Offering --> System: List of offerings
System --> Admin: List of offerings

Instructor -> System: viewAvailableOfferings()
System -> Offering: getOfferings()
Offering --> System: List of available Offerings
System --> Instructor: List of available Offerings

Instructor -> System: acceptOffering(Offering)
alt Success
    System -> Offering: setOfferingStatus(taken)
    Offering --> System: Acceptance Confirmation
    System --> Instructor: Acceptance Confirmation
else Failure
    System --> Instructor: Error message
end

Admin -> System: updateOffering(Location, Schedule, Instructor, Lesson)
alt Success
    System -> Offering: setOffering(Location, Schedule, Instructor, Lesson)
    Offering --> System: Update Confirmation
    System --> Admin: Update Confirmation
else Failure
    System --> Admin: Error message
end

@enduml
