@startuml Use Case Diagram
left to right direction
' skinparam linetype ortho


actor Public
actor Client
actor Instructor
actor Admin

rectangle System {
    usecase "Register" as Register
    usecase "Take Lesson" as TakeOffer
    usecase "View Offerings" as ViewOfferings
    usecase "Login" as Login
    usecase "Create Booking" as CreateBooking
    usecase "Cancel Booking" as CancelBooking
    usecase "Register Client" as RegisterClient
    usecase "Register Instructor" as RegisterInstructor
    usecase "View Bookings" as ViewBookings
    usecase "Manage Accounts" as ManageAccount
    usecase "Create Offering" as CreateOffer
    usecase "Manage Bookings" as ManageBooking
}

Public --> ViewOfferings
Public --> Register
Public --> Login
Client --> ManageBooking
Client --> ViewOfferings
Client --> ViewBookings

ManageBooking ..> CreateBooking
ManageBooking ..> CancelBooking

Register ..> RegisterClient
Register ..> RegisterInstructor

Instructor --> TakeOffer

Admin --> CreateOffer
Admin --> ManageAccount
Admin --> ViewBookings
Admin --> ManageBooking
@enduml
