@startuml System Sequence Diagram: Offering Creation
title System Sequence Diagram: Offering Creation

actor Admin
participant System
Admin -> System: login(username,password)
System --> Admin: confirmation message
Admin -> System: adminCreateOffering(Lesson, LocationId, TimeSlots, Capacity, IsPrivate, StartDate, EndDate)
alt All validations pass
    System --> Admin: Confirmation message
else Validation fails
    System --> Admin: Error message
end

@enduml
