@startuml SSD-Failure: Create Booking
title SSD-Failure: Create Booking

actor Client
actor System

System -> System: userType := getCurrentUserType()
Client <-- System: display Public operations
alt Successful
    Client -> System: selectOperation(loginOperationId)
    alt Successful
        Client -> System: login(username, password)
        Client <-- System: login success
    else Failure
        Client <-- System: authentication rejected
    end
else Failure
    Client <-- System: invalid operation id
end
...
loop
    System -> System: userType := getCurrentUserType()
    Client <-- System: display Client operations
    alt Successful
        Client -> System: selectOperation(createBookingOperationId)
        System -> System: clientViewPublicOfferings()
        Client <-- System: display Client Offerings
    else Failure
        Client <-- System: invalid operation id
    end
    alt Successful
        Client -> System: createBooking(offeringId)
        Client <-- System: success
    else Failure
        Client <-- System: error while creating booking
    end
end

@enduml